# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('promo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('orderid', models.IntegerField(unique=True)),
                ('checkin', models.DateField(max_length=100)),
                ('checkout', models.DateField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('amenties', models.CharField(max_length=100)),
                ('amentiestotal', models.IntegerField()),
                ('promodiscount', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
